[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mss>=10.0.0",
    "ocr-nanonets-wrapper>=1.1",
    "pillow>=11.3.0",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.1.1",
    "watchdog>=6.0.0",
]
